name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Analysing the code with flake8
      run: |
        docker run -it -v $(pwd):/code mvantellingen/python-lint:latest flake8 --max-line-length=128
